/*
Copyright © 2026 Mulga Defense Corporation

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package install

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/mulgadc/spinifex/cmd/installer/firstboot"
)

const (
	mountRoot = "/mnt/spinifex-install"
	efiPart   = mountRoot + "/boot/efi"
)

// Run executes all installation steps in order. It is intentionally sequential
// and explicit — each step is visible in logs so failures are easy to diagnose.
func Run(cfg *Config) error {
	steps := []struct {
		name string
		fn   func() error
	}{
		{"partition disk", func() error { return partitionDisk(cfg.Disk) }},
		{"format partitions", func() error { return formatPartitions(cfg.Disk) }},
		{"mount partitions", func() error { return mountPartitions(cfg.Disk) }},
		{"debootstrap", debootstrap},
		{"install spinifex", func() error { return installSpinifex(cfg) }},
		{"write network config", func() error { return writeNetworkConfig(cfg) }},
		{"write firstboot service", func() error { return firstboot.Write(mountRoot, cfg.toFirstbootConfig()) }},
		{"install bootloader", func() error { return installBootloader(cfg.Disk) }},
		{"install CA cert", func() error { return installCACert(cfg) }},
		{"unmount", unmount},
	}

	for _, s := range steps {
		slog.Info("installer", "step", s.name)
		if err := s.fn(); err != nil {
			return fmt.Errorf("step %q: %w", s.name, err)
		}
	}

	slog.Info("installation complete — rebooting")
	return reboot()
}

func partitionDisk(disk string) error {
	// GPT table with a 512MB EFI partition and the rest as root.
	return run("parted", "--script", disk,
		"mklabel", "gpt",
		"mkpart", "ESP", "fat32", "1MiB", "513MiB",
		"set", "1", "esp", "on",
		"mkpart", "root", "ext4", "513MiB", "100%",
	)
}

func formatPartitions(disk string) error {
	efi, root := partitionPaths(disk)
	if err := run("mkfs.fat", "-F32", efi); err != nil {
		return err
	}
	return run("mkfs.ext4", "-F", root)
}

func mountPartitions(disk string) error {
	_, root := partitionPaths(disk)
	if err := os.MkdirAll(mountRoot, 0o755); err != nil {
		return err
	}
	if err := run("mount", root, mountRoot); err != nil {
		return err
	}
	if err := os.MkdirAll(efiPart, 0o755); err != nil {
		return err
	}
	efi, _ := partitionPaths(disk)
	return run("mount", efi, efiPart)
}

func debootstrap() error {
	return run("debootstrap", "--arch=amd64", "bookworm", mountRoot)
}

func installSpinifex(cfg *Config) error {
	// Copy the spinifex binary from the ISO's live environment into the target.
	spxBin, err := exec.LookPath("spinifex")
	if err != nil {
		return fmt.Errorf("spinifex binary not found on ISO: %w", err)
	}
	dest := filepath.Join(mountRoot, "usr/local/bin/spinifex")
	if err := copyFile(spxBin, dest, 0o755); err != nil {
		return err
	}

	// Run setup.sh inside a chroot to install dependencies and systemd units.
	setupSh := "/usr/local/share/spinifex/setup.sh"
	return run("chroot", mountRoot, "bash", setupSh, "--offline")
}

func writeNetworkConfig(cfg *Config) error {
	// Write a simple /etc/network/interfaces for the management interface.
	// The OVN interface is left unconfigured here — setup-ovn.sh handles it
	// on first boot.
	content := fmt.Sprintf(`# Generated by Spinifex installer
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address %s
    netmask %s
    gateway %s
`, cfg.ManagementIP, cfg.SubnetMask, cfg.Gateway)

	path := filepath.Join(mountRoot, "etc/network/interfaces")
	return os.WriteFile(path, []byte(content), 0o644)
}

func installBootloader(disk string) error {
	// Install GRUB for both BIOS (grub-pc) and UEFI (grub-efi-amd64).
	if err := run("chroot", mountRoot,
		"grub-install", "--target=x86_64-efi",
		"--efi-directory=/boot/efi",
		"--bootloader-id=spinifex",
		"--recheck",
	); err != nil {
		return err
	}
	if err := run("chroot", mountRoot,
		"grub-install", "--target=i386-pc", disk,
	); err != nil {
		return err
	}
	return run("chroot", mountRoot, "update-grub")
}

func installCACert(cfg *Config) error {
	if !cfg.HasCACert || cfg.CACert == "" {
		return nil
	}
	certPath := filepath.Join(mountRoot, "usr/local/share/ca-certificates/spinifex-ca.crt")
	if err := os.WriteFile(certPath, []byte(cfg.CACert), 0o644); err != nil {
		return err
	}
	return run("chroot", mountRoot, "update-ca-certificates")
}

func unmount() error {
	if err := run("umount", efiPart); err != nil {
		return err
	}
	return run("umount", mountRoot)
}

func reboot() error {
	return run("reboot")
}

// toFirstbootConfig maps installer Config to the firstboot package's Config.
func (c *Config) toFirstbootConfig() firstboot.Config {
	return firstboot.Config{
		Hostname:     c.Hostname,
		OVNInterface: c.OVNInterface,
		ManagementIP: c.ManagementIP,
		ClusterRole:  c.ClusterRole,
		JoinAddr:     c.JoinAddr,
	}
}

// partitionPaths returns the EFI and root partition device paths for a given
// disk. Handles both /dev/sdX (→ /dev/sdX1, /dev/sdX2) and /dev/nvmeXnY
// (→ /dev/nvmeXnYp1, /dev/nvmeXnYp2).
func partitionPaths(disk string) (efi, root string) {
	// NVMe devices use a 'p' separator before the partition number.
	if len(disk) > 0 && disk[len(disk)-1] >= '0' && disk[len(disk)-1] <= '9' {
		return disk + "p1", disk + "p2"
	}
	return disk + "1", disk + "2"
}

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func copyFile(src, dst string, mode os.FileMode) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, mode)
}
