---
galaxy_info:
  role_name: install
  description: Invoke setup.sh and setup-ovn.sh to install Spinifex into production paths.
  license: BSD-3-Clause
  min_ansible_version: "2.14"
dependencies: []
