# Domain configration file in TOML format.
version = "1.0"
region = "ap-southeast-2"

access_key = "AKIAIOSFODNN7EXAMPLE"
secret_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

[daemon]
host = "0.0.0.0:4432"
sslkey = "config/server.key"
sslcert = "config/server.pem"

[nats]
host = "0.0.0.0:4222"

[nats.acl]
token = "your-nats-token"

[nats.sub]
subject = "ec2.>"

[predastore]
host = "0.0.0.0:8443"
region = "ap-southeast-2"
bucket = "predastore"
access_key = "AKIAIOSFODNN7EXAMPLE"
secret_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"