# Domain configration file in TOML format.
version = "1.0"
region = "ap-southeast-2"

[[daemon]]
host = "0.0.0.0:4432"
sslkey = "config/server.key"
sslcert = "config/server.pem"

[[nats]]
host = "0.0.0.0:4222"

[[nats.acl]]
token = "your-nats-token"

[[nats.sub]]
subject = "ec2.>"
