// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// biome-ignore-all lint assist: Auto-generated file

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthS3LsIndexRouteImport } from './routes/_auth/s3/ls/index'
import { Route as AuthEc2keyImportKeyPairRouteImport } from './routes/_auth/ec2/(key)/import-key-pair'
import { Route as AuthEc2keyCreateKeyPairRouteImport } from './routes/_auth/ec2/(key)/create-key-pair'
import { Route as AuthEc2instancesRunInstancesRouteImport } from './routes/_auth/ec2/(instances)/run-instances'
import { Route as AuthS3LsBucketRouteRouteImport } from './routes/_auth/s3/ls/$bucket/route'
import { Route as AuthS3LsBucketIndexRouteImport } from './routes/_auth/s3/ls/$bucket/index'
import { Route as AuthEc2volumesDescribeVolumesIndexRouteImport } from './routes/_auth/ec2/(volumes)/describe-volumes/index'
import { Route as AuthEc2keyDescribeKeyPairsIndexRouteImport } from './routes/_auth/ec2/(key)/describe-key-pairs/index'
import { Route as AuthEc2instancesDescribeInstancesIndexRouteImport } from './routes/_auth/ec2/(instances)/describe-instances/index'
import { Route as AuthEc2imagesDescribeImagesIndexRouteImport } from './routes/_auth/ec2/(images)/describe-images/index'
import { Route as AuthS3LsBucketSplatRouteImport } from './routes/_auth/s3/ls/$bucket/$'
import { Route as AuthEc2volumesDescribeVolumesIdRouteImport } from './routes/_auth/ec2/(volumes)/describe-volumes/$id'
import { Route as AuthEc2keyDescribeKeyPairsIdRouteImport } from './routes/_auth/ec2/(key)/describe-key-pairs/$id'
import { Route as AuthEc2instancesDescribeInstancesIdRouteImport } from './routes/_auth/ec2/(instances)/describe-instances/$id'
import { Route as AuthEc2imagesDescribeImagesIdRouteImport } from './routes/_auth/ec2/(images)/describe-images/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3LsIndexRoute = AuthS3LsIndexRouteImport.update({
  id: '/s3/ls/',
  path: '/s3/ls/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2keyImportKeyPairRoute = AuthEc2keyImportKeyPairRouteImport.update({
  id: '/ec2/(key)/import-key-pair',
  path: '/ec2/import-key-pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2keyCreateKeyPairRoute = AuthEc2keyCreateKeyPairRouteImport.update({
  id: '/ec2/(key)/create-key-pair',
  path: '/ec2/create-key-pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2instancesRunInstancesRoute =
  AuthEc2instancesRunInstancesRouteImport.update({
    id: '/ec2/(instances)/run-instances',
    path: '/ec2/run-instances',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthS3LsBucketRouteRoute = AuthS3LsBucketRouteRouteImport.update({
  id: '/s3/ls/$bucket',
  path: '/s3/ls/$bucket',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3LsBucketIndexRoute = AuthS3LsBucketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthS3LsBucketRouteRoute,
} as any)
const AuthEc2volumesDescribeVolumesIndexRoute =
  AuthEc2volumesDescribeVolumesIndexRouteImport.update({
    id: '/ec2/(volumes)/describe-volumes/',
    path: '/ec2/describe-volumes/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2keyDescribeKeyPairsIndexRoute =
  AuthEc2keyDescribeKeyPairsIndexRouteImport.update({
    id: '/ec2/(key)/describe-key-pairs/',
    path: '/ec2/describe-key-pairs/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2instancesDescribeInstancesIndexRoute =
  AuthEc2instancesDescribeInstancesIndexRouteImport.update({
    id: '/ec2/(instances)/describe-instances/',
    path: '/ec2/describe-instances/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2imagesDescribeImagesIndexRoute =
  AuthEc2imagesDescribeImagesIndexRouteImport.update({
    id: '/ec2/(images)/describe-images/',
    path: '/ec2/describe-images/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthS3LsBucketSplatRoute = AuthS3LsBucketSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthS3LsBucketRouteRoute,
} as any)
const AuthEc2volumesDescribeVolumesIdRoute =
  AuthEc2volumesDescribeVolumesIdRouteImport.update({
    id: '/ec2/(volumes)/describe-volumes/$id',
    path: '/ec2/describe-volumes/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2keyDescribeKeyPairsIdRoute =
  AuthEc2keyDescribeKeyPairsIdRouteImport.update({
    id: '/ec2/(key)/describe-key-pairs/$id',
    path: '/ec2/describe-key-pairs/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2instancesDescribeInstancesIdRoute =
  AuthEc2instancesDescribeInstancesIdRouteImport.update({
    id: '/ec2/(instances)/describe-instances/$id',
    path: '/ec2/describe-instances/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2imagesDescribeImagesIdRoute =
  AuthEc2imagesDescribeImagesIdRouteImport.update({
    id: '/ec2/(images)/describe-images/$id',
    path: '/ec2/describe-images/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/s3/ls/$bucket': typeof AuthS3LsBucketRouteRouteWithChildren
  '/ec2/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/ec2/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/ec2/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/s3/ls/': typeof AuthS3LsIndexRoute
  '/ec2/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/ec2/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/ec2/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/ec2/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/ec2/describe-images/': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/ec2/describe-instances/': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/ec2/describe-key-pairs/': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/ec2/describe-volumes/': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/s3/ls/$bucket/': typeof AuthS3LsBucketIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/ec2/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/ec2/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/ec2/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/s3/ls': typeof AuthS3LsIndexRoute
  '/ec2/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/ec2/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/ec2/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/ec2/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/ec2/describe-images': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/ec2/describe-instances': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/ec2/describe-key-pairs': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/ec2/describe-volumes': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/s3/ls/$bucket': typeof AuthS3LsBucketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/s3/ls/$bucket': typeof AuthS3LsBucketRouteRouteWithChildren
  '/_auth/ec2/(instances)/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/_auth/ec2/(key)/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/_auth/ec2/(key)/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/_auth/s3/ls/': typeof AuthS3LsIndexRoute
  '/_auth/ec2/(images)/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/_auth/ec2/(instances)/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/_auth/ec2/(key)/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/_auth/ec2/(volumes)/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/_auth/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/_auth/ec2/(images)/describe-images/': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/_auth/ec2/(instances)/describe-instances/': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/_auth/ec2/(key)/describe-key-pairs/': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/_auth/ec2/(volumes)/describe-volumes/': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/_auth/s3/ls/$bucket/': typeof AuthS3LsBucketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/s3/ls/$bucket'
    | '/ec2/run-instances'
    | '/ec2/create-key-pair'
    | '/ec2/import-key-pair'
    | '/s3/ls/'
    | '/ec2/describe-images/$id'
    | '/ec2/describe-instances/$id'
    | '/ec2/describe-key-pairs/$id'
    | '/ec2/describe-volumes/$id'
    | '/s3/ls/$bucket/$'
    | '/ec2/describe-images/'
    | '/ec2/describe-instances/'
    | '/ec2/describe-key-pairs/'
    | '/ec2/describe-volumes/'
    | '/s3/ls/$bucket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/ec2/run-instances'
    | '/ec2/create-key-pair'
    | '/ec2/import-key-pair'
    | '/s3/ls'
    | '/ec2/describe-images/$id'
    | '/ec2/describe-instances/$id'
    | '/ec2/describe-key-pairs/$id'
    | '/ec2/describe-volumes/$id'
    | '/s3/ls/$bucket/$'
    | '/ec2/describe-images'
    | '/ec2/describe-instances'
    | '/ec2/describe-key-pairs'
    | '/ec2/describe-volumes'
    | '/s3/ls/$bucket'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/s3/ls/$bucket'
    | '/_auth/ec2/(instances)/run-instances'
    | '/_auth/ec2/(key)/create-key-pair'
    | '/_auth/ec2/(key)/import-key-pair'
    | '/_auth/s3/ls/'
    | '/_auth/ec2/(images)/describe-images/$id'
    | '/_auth/ec2/(instances)/describe-instances/$id'
    | '/_auth/ec2/(key)/describe-key-pairs/$id'
    | '/_auth/ec2/(volumes)/describe-volumes/$id'
    | '/_auth/s3/ls/$bucket/$'
    | '/_auth/ec2/(images)/describe-images/'
    | '/_auth/ec2/(instances)/describe-instances/'
    | '/_auth/ec2/(key)/describe-key-pairs/'
    | '/_auth/ec2/(volumes)/describe-volumes/'
    | '/_auth/s3/ls/$bucket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/': {
      id: '/_auth/s3/ls/'
      path: '/s3/ls'
      fullPath: '/s3/ls/'
      preLoaderRoute: typeof AuthS3LsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/import-key-pair': {
      id: '/_auth/ec2/(key)/import-key-pair'
      path: '/ec2/import-key-pair'
      fullPath: '/ec2/import-key-pair'
      preLoaderRoute: typeof AuthEc2keyImportKeyPairRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/create-key-pair': {
      id: '/_auth/ec2/(key)/create-key-pair'
      path: '/ec2/create-key-pair'
      fullPath: '/ec2/create-key-pair'
      preLoaderRoute: typeof AuthEc2keyCreateKeyPairRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/run-instances': {
      id: '/_auth/ec2/(instances)/run-instances'
      path: '/ec2/run-instances'
      fullPath: '/ec2/run-instances'
      preLoaderRoute: typeof AuthEc2instancesRunInstancesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket': {
      id: '/_auth/s3/ls/$bucket'
      path: '/s3/ls/$bucket'
      fullPath: '/s3/ls/$bucket'
      preLoaderRoute: typeof AuthS3LsBucketRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket/': {
      id: '/_auth/s3/ls/$bucket/'
      path: '/'
      fullPath: '/s3/ls/$bucket/'
      preLoaderRoute: typeof AuthS3LsBucketIndexRouteImport
      parentRoute: typeof AuthS3LsBucketRouteRoute
    }
    '/_auth/ec2/(volumes)/describe-volumes/': {
      id: '/_auth/ec2/(volumes)/describe-volumes/'
      path: '/ec2/describe-volumes'
      fullPath: '/ec2/describe-volumes/'
      preLoaderRoute: typeof AuthEc2volumesDescribeVolumesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/describe-key-pairs/': {
      id: '/_auth/ec2/(key)/describe-key-pairs/'
      path: '/ec2/describe-key-pairs'
      fullPath: '/ec2/describe-key-pairs/'
      preLoaderRoute: typeof AuthEc2keyDescribeKeyPairsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/describe-instances/': {
      id: '/_auth/ec2/(instances)/describe-instances/'
      path: '/ec2/describe-instances'
      fullPath: '/ec2/describe-instances/'
      preLoaderRoute: typeof AuthEc2instancesDescribeInstancesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(images)/describe-images/': {
      id: '/_auth/ec2/(images)/describe-images/'
      path: '/ec2/describe-images'
      fullPath: '/ec2/describe-images/'
      preLoaderRoute: typeof AuthEc2imagesDescribeImagesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket/$': {
      id: '/_auth/s3/ls/$bucket/$'
      path: '/$'
      fullPath: '/s3/ls/$bucket/$'
      preLoaderRoute: typeof AuthS3LsBucketSplatRouteImport
      parentRoute: typeof AuthS3LsBucketRouteRoute
    }
    '/_auth/ec2/(volumes)/describe-volumes/$id': {
      id: '/_auth/ec2/(volumes)/describe-volumes/$id'
      path: '/ec2/describe-volumes/$id'
      fullPath: '/ec2/describe-volumes/$id'
      preLoaderRoute: typeof AuthEc2volumesDescribeVolumesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/describe-key-pairs/$id': {
      id: '/_auth/ec2/(key)/describe-key-pairs/$id'
      path: '/ec2/describe-key-pairs/$id'
      fullPath: '/ec2/describe-key-pairs/$id'
      preLoaderRoute: typeof AuthEc2keyDescribeKeyPairsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/describe-instances/$id': {
      id: '/_auth/ec2/(instances)/describe-instances/$id'
      path: '/ec2/describe-instances/$id'
      fullPath: '/ec2/describe-instances/$id'
      preLoaderRoute: typeof AuthEc2instancesDescribeInstancesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(images)/describe-images/$id': {
      id: '/_auth/ec2/(images)/describe-images/$id'
      path: '/ec2/describe-images/$id'
      fullPath: '/ec2/describe-images/$id'
      preLoaderRoute: typeof AuthEc2imagesDescribeImagesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthS3LsBucketRouteRouteChildren {
  AuthS3LsBucketSplatRoute: typeof AuthS3LsBucketSplatRoute
  AuthS3LsBucketIndexRoute: typeof AuthS3LsBucketIndexRoute
}

const AuthS3LsBucketRouteRouteChildren: AuthS3LsBucketRouteRouteChildren = {
  AuthS3LsBucketSplatRoute: AuthS3LsBucketSplatRoute,
  AuthS3LsBucketIndexRoute: AuthS3LsBucketIndexRoute,
}

const AuthS3LsBucketRouteRouteWithChildren =
  AuthS3LsBucketRouteRoute._addFileChildren(AuthS3LsBucketRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthS3LsBucketRouteRoute: typeof AuthS3LsBucketRouteRouteWithChildren
  AuthEc2instancesRunInstancesRoute: typeof AuthEc2instancesRunInstancesRoute
  AuthEc2keyCreateKeyPairRoute: typeof AuthEc2keyCreateKeyPairRoute
  AuthEc2keyImportKeyPairRoute: typeof AuthEc2keyImportKeyPairRoute
  AuthS3LsIndexRoute: typeof AuthS3LsIndexRoute
  AuthEc2imagesDescribeImagesIdRoute: typeof AuthEc2imagesDescribeImagesIdRoute
  AuthEc2instancesDescribeInstancesIdRoute: typeof AuthEc2instancesDescribeInstancesIdRoute
  AuthEc2keyDescribeKeyPairsIdRoute: typeof AuthEc2keyDescribeKeyPairsIdRoute
  AuthEc2volumesDescribeVolumesIdRoute: typeof AuthEc2volumesDescribeVolumesIdRoute
  AuthEc2imagesDescribeImagesIndexRoute: typeof AuthEc2imagesDescribeImagesIndexRoute
  AuthEc2instancesDescribeInstancesIndexRoute: typeof AuthEc2instancesDescribeInstancesIndexRoute
  AuthEc2keyDescribeKeyPairsIndexRoute: typeof AuthEc2keyDescribeKeyPairsIndexRoute
  AuthEc2volumesDescribeVolumesIndexRoute: typeof AuthEc2volumesDescribeVolumesIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthS3LsBucketRouteRoute: AuthS3LsBucketRouteRouteWithChildren,
  AuthEc2instancesRunInstancesRoute: AuthEc2instancesRunInstancesRoute,
  AuthEc2keyCreateKeyPairRoute: AuthEc2keyCreateKeyPairRoute,
  AuthEc2keyImportKeyPairRoute: AuthEc2keyImportKeyPairRoute,
  AuthS3LsIndexRoute: AuthS3LsIndexRoute,
  AuthEc2imagesDescribeImagesIdRoute: AuthEc2imagesDescribeImagesIdRoute,
  AuthEc2instancesDescribeInstancesIdRoute:
    AuthEc2instancesDescribeInstancesIdRoute,
  AuthEc2keyDescribeKeyPairsIdRoute: AuthEc2keyDescribeKeyPairsIdRoute,
  AuthEc2volumesDescribeVolumesIdRoute: AuthEc2volumesDescribeVolumesIdRoute,
  AuthEc2imagesDescribeImagesIndexRoute: AuthEc2imagesDescribeImagesIndexRoute,
  AuthEc2instancesDescribeInstancesIndexRoute:
    AuthEc2instancesDescribeInstancesIndexRoute,
  AuthEc2keyDescribeKeyPairsIndexRoute: AuthEc2keyDescribeKeyPairsIndexRoute,
  AuthEc2volumesDescribeVolumesIndexRoute:
    AuthEc2volumesDescribeVolumesIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
